### ISSUE TITLE
OFL?

### ISSUE THREAD

**Issue by davelab6** [MihailJP/oldsindhi#1]
Would you consider switching to the SIL Open Font License, with no reserved font name? :)

**Comment by MihailJP** [comment]
Licensing under SIL OFL makes sense, but I prefer permissive ones such as FreeBSD License rather than copyleft ones (e.g. GNU GPL). Currently the font is licensed under FreeBSD License, but I should consider switching to the MIT License.

**Comment by davelab6** [comment]
The OFL is required for the font to be included in Google Fonts....

**Comment by MihailJP** [comment]
Yeah, I understand why it matters. That is one of the best way using fonts online.
If it is okay I will switch to dual licensing with OFL and MIT License.

**Comment by davelab6** [comment]
Sounds good
